services:

  api:
    depends_on:
      postgres:
        condition: service_started
      redis:
        condition: service_healthy
    build:
      context: .
      dockerfile: Dockerfile
    container_name: issueforge-api
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - DB_HOST=postgres

  postgres:
    image: postgres:17-alpine
    container_name: issueforge-postgres
    ports:
      -  "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    restart: unless-stopped

  prometheus:
    image: prom/prometheus
    container_name: issueforge-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: issueforge-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      
  redis:
    image: redis:7-alpine
    container_name: issueforge-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - redis_data:/data
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  postgres_data:
  redis_data:
  grafana_data: