services:

  prometheus:
    image: prom/prometheus
    container_name: issueforge-prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml

  grafana:
    image: grafana/grafana
    container_name: issueforge-grafana
    ports:
      - "3000:3000"
    volumes:
      - grafana_data:/var/lib/grafana
      
  redis:
    image: redis:7-alpine
    container_name: issueforge-redis
    ports:
      - "6379:6379"
    command: redis-server --appendonly yes
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data:
  grafana_data: