// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: activities.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createActivity = `-- name: CreateActivity :one
INSERT INTO issue_activities(
    issue_id, 
    actor_id, 
    activity_type, 
    field_name, 
    old_value, 
    new_value
) VALUES (
    $1,$2,$3,$4,$5,$6
)
RETURNING id, issue_id, actor_id, activity_type, field_name, old_value, new_value, created_at
`

type CreateActivityParams struct {
	IssueID      int64        `json:"issue_id"`
	ActorID      int64        `json:"actor_id"`
	ActivityType ActivityType `json:"activity_type"`
	FieldName    pgtype.Text  `json:"field_name"`
	OldValue     pgtype.Text  `json:"old_value"`
	NewValue     pgtype.Text  `json:"new_value"`
}

func (q *Queries) CreateActivity(ctx context.Context, arg CreateActivityParams) (IssueActivity, error) {
	row := q.db.QueryRow(ctx, createActivity,
		arg.IssueID,
		arg.ActorID,
		arg.ActivityType,
		arg.FieldName,
		arg.OldValue,
		arg.NewValue,
	)
	var i IssueActivity
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.ActorID,
		&i.ActivityType,
		&i.FieldName,
		&i.OldValue,
		&i.NewValue,
		&i.CreatedAt,
	)
	return i, err
}

const listIssueActivities = `-- name: ListIssueActivities :many
SELECT ia.id, ia.issue_id, ia.actor_id, ia.activity_type, ia.field_name, ia.old_value, ia.new_value, ia.created_at,
       u_actor.fullname AS actor_name, u_actor.username AS actor_username
FROM issue_activities ia
INNER JOIN users u_actor ON ia.actor_id = u_actor.id
INNER JOIN issues i ON ia.issue_id = i.id
WHERE ia.issue_id = $1
ORDER BY ia.created_at DESC
LIMIT $2
OFFSET $3
`

type ListIssueActivitiesParams struct {
	IssueID int64 `json:"issue_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type ListIssueActivitiesRow struct {
	ID            int64              `json:"id"`
	IssueID       int64              `json:"issue_id"`
	ActorID       int64              `json:"actor_id"`
	ActivityType  ActivityType       `json:"activity_type"`
	FieldName     pgtype.Text        `json:"field_name"`
	OldValue      pgtype.Text        `json:"old_value"`
	NewValue      pgtype.Text        `json:"new_value"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	ActorName     string             `json:"actor_name"`
	ActorUsername string             `json:"actor_username"`
}

func (q *Queries) ListIssueActivities(ctx context.Context, arg ListIssueActivitiesParams) ([]ListIssueActivitiesRow, error) {
	rows, err := q.db.Query(ctx, listIssueActivities, arg.IssueID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueActivitiesRow
	for rows.Next() {
		var i ListIssueActivitiesRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.ActorID,
			&i.ActivityType,
			&i.FieldName,
			&i.OldValue,
			&i.NewValue,
			&i.CreatedAt,
			&i.ActorName,
			&i.ActorUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
