// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: comments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createComment = `-- name: CreateComment :one
INSERT INTO comments(
    issue_id,
    author_id,
    parent_comment_id,
    content
) VALUES (
    $1, $2, $3, $4
)
RETURNING id, issue_id, author_id, parent_comment_id, content, is_edited, created_at, updated_at
`

type CreateCommentParams struct {
	IssueID         int64       `json:"issue_id"`
	AuthorID        int64       `json:"author_id"`
	ParentCommentID pgtype.Int8 `json:"parent_comment_id"`
	Content         string      `json:"content"`
}

func (q *Queries) CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, createComment,
		arg.IssueID,
		arg.AuthorID,
		arg.ParentCommentID,
		arg.Content,
	)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.ParentCommentID,
		&i.Content,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const deleteComment = `-- name: DeleteComment :one
DELETE FROM comments
WHERE id = $1
RETURNING id
`

func (q *Queries) DeleteComment(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteComment, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getCommentByID = `-- name: GetCommentByID :one
SELECT c.id, c.issue_id, c.author_id, u.display_name as author_name, c.parent_comment_id, c.content, c.is_edited, c.created_at, c.updated_at
FROM comments c
JOIN users u ON c.author_id = u.id
WHERE c.id = $1
`

type GetCommentByIDRow struct {
	ID              int64              `json:"id"`
	IssueID         int64              `json:"issue_id"`
	AuthorID        int64              `json:"author_id"`
	AuthorName      string             `json:"author_name"`
	ParentCommentID pgtype.Int8        `json:"parent_comment_id"`
	Content         string             `json:"content"`
	IsEdited        bool               `json:"is_edited"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetCommentByID(ctx context.Context, id int64) (GetCommentByIDRow, error) {
	row := q.db.QueryRow(ctx, getCommentByID, id)
	var i GetCommentByIDRow
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.AuthorName,
		&i.ParentCommentID,
		&i.Content,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listIssueComments = `-- name: ListIssueComments :many
SELECT c.id, c.issue_id, c.author_id, u.display_name as author_name, c.parent_comment_id, c.content, c.is_edited, c.created_at, c.updated_at
FROM comments c
JOIN users u
ON c.author_id = u.id
WHERE c.issue_id = $1
ORDER BY c.created_at ASC
LIMIT $2 OFFSET $3
`

type ListIssueCommentsParams struct {
	IssueID int64 `json:"issue_id"`
	Limit   int32 `json:"limit"`
	Offset  int32 `json:"offset"`
}

type ListIssueCommentsRow struct {
	ID              int64              `json:"id"`
	IssueID         int64              `json:"issue_id"`
	AuthorID        int64              `json:"author_id"`
	AuthorName      string             `json:"author_name"`
	ParentCommentID pgtype.Int8        `json:"parent_comment_id"`
	Content         string             `json:"content"`
	IsEdited        bool               `json:"is_edited"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListIssueComments(ctx context.Context, arg ListIssueCommentsParams) ([]ListIssueCommentsRow, error) {
	rows, err := q.db.Query(ctx, listIssueComments, arg.IssueID, arg.Limit, arg.Offset)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueCommentsRow
	for rows.Next() {
		var i ListIssueCommentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.AuthorID,
			&i.AuthorName,
			&i.ParentCommentID,
			&i.Content,
			&i.IsEdited,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateComment = `-- name: UpdateComment :one
UPDATE comments
SET content = $2, is_edited = TRUE, updated_at = NOW()
WHERE id = $1 AND author_id = $3
RETURNING id, issue_id, author_id, parent_comment_id, content, is_edited, created_at, updated_at
`

type UpdateCommentParams struct {
	ID       int64  `json:"id"`
	Content  string `json:"content"`
	AuthorID int64  `json:"author_id"`
}

func (q *Queries) UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error) {
	row := q.db.QueryRow(ctx, updateComment, arg.ID, arg.Content, arg.AuthorID)
	var i Comment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.AuthorID,
		&i.ParentCommentID,
		&i.Content,
		&i.IsEdited,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
