// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issue_attachments.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createAttachment = `-- name: CreateAttachment :one
INSERT INTO issue_attachments(
    issue_id, 
    comment_id, 
    uploaded_by, 
    original_name, 
    storage_key, 
    resource_type, 
    mime_type, 
    file_size
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
)
RETURNING id, issue_id, comment_id, uploaded_by, original_name, storage_key, resource_type, mime_type, file_size, created_at, deleted_at
`

type CreateAttachmentParams struct {
	IssueID      int64       `json:"issue_id"`
	CommentID    pgtype.Int8 `json:"comment_id"`
	UploadedBy   int64       `json:"uploaded_by"`
	OriginalName string      `json:"original_name"`
	StorageKey   string      `json:"storage_key"`
	ResourceType string      `json:"resource_type"`
	MimeType     string      `json:"mime_type"`
	FileSize     int64       `json:"file_size"`
}

func (q *Queries) CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (IssueAttachment, error) {
	row := q.db.QueryRow(ctx, createAttachment,
		arg.IssueID,
		arg.CommentID,
		arg.UploadedBy,
		arg.OriginalName,
		arg.StorageKey,
		arg.ResourceType,
		arg.MimeType,
		arg.FileSize,
	)
	var i IssueAttachment
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.CommentID,
		&i.UploadedBy,
		&i.OriginalName,
		&i.StorageKey,
		&i.ResourceType,
		&i.MimeType,
		&i.FileSize,
		&i.CreatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAttachmentByID = `-- name: GetAttachmentByID :one
SELECT ia.id, ia.issue_id, ia.comment_id, ia.uploaded_by, ia.original_name, ia.storage_key, ia.resource_type, ia.mime_type, ia.file_size, ia.created_at, ia.deleted_at,
    uploader.fullname AS uploader_name, uploader.username AS uploader_username
FROM issue_attachments ia
JOIN users uploader ON ia.uploaded_by = uploader.id
WHERE ia.id = $1 AND ia.deleted_at IS NULL
`

type GetAttachmentByIDRow struct {
	ID               int64              `json:"id"`
	IssueID          int64              `json:"issue_id"`
	CommentID        pgtype.Int8        `json:"comment_id"`
	UploadedBy       int64              `json:"uploaded_by"`
	OriginalName     string             `json:"original_name"`
	StorageKey       string             `json:"storage_key"`
	ResourceType     string             `json:"resource_type"`
	MimeType         string             `json:"mime_type"`
	FileSize         int64              `json:"file_size"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	UploaderName     string             `json:"uploader_name"`
	UploaderUsername string             `json:"uploader_username"`
}

func (q *Queries) GetAttachmentByID(ctx context.Context, id int64) (GetAttachmentByIDRow, error) {
	row := q.db.QueryRow(ctx, getAttachmentByID, id)
	var i GetAttachmentByIDRow
	err := row.Scan(
		&i.ID,
		&i.IssueID,
		&i.CommentID,
		&i.UploadedBy,
		&i.OriginalName,
		&i.StorageKey,
		&i.ResourceType,
		&i.MimeType,
		&i.FileSize,
		&i.CreatedAt,
		&i.DeletedAt,
		&i.UploaderName,
		&i.UploaderUsername,
	)
	return i, err
}

const listCommentAttachments = `-- name: ListCommentAttachments :many
SELECT ia.id, ia.issue_id, ia.comment_id, ia.uploaded_by, ia.original_name, ia.storage_key, ia.resource_type, ia.mime_type, ia.file_size, ia.created_at,
    uploader.fullname AS uploader_name, uploader.username AS uploader_username
FROM issue_attachments ia
JOIN users uploader ON ia.uploaded_by = uploader.id
WHERE ia.comment_id = $1 AND ia.deleted_at IS NULL
ORDER BY ia.created_at ASC
`

type ListCommentAttachmentsRow struct {
	ID               int64              `json:"id"`
	IssueID          int64              `json:"issue_id"`
	CommentID        pgtype.Int8        `json:"comment_id"`
	UploadedBy       int64              `json:"uploaded_by"`
	OriginalName     string             `json:"original_name"`
	StorageKey       string             `json:"storage_key"`
	ResourceType     string             `json:"resource_type"`
	MimeType         string             `json:"mime_type"`
	FileSize         int64              `json:"file_size"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UploaderName     string             `json:"uploader_name"`
	UploaderUsername string             `json:"uploader_username"`
}

func (q *Queries) ListCommentAttachments(ctx context.Context, commentID pgtype.Int8) ([]ListCommentAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listCommentAttachments, commentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCommentAttachmentsRow
	for rows.Next() {
		var i ListCommentAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.CommentID,
			&i.UploadedBy,
			&i.OriginalName,
			&i.StorageKey,
			&i.ResourceType,
			&i.MimeType,
			&i.FileSize,
			&i.CreatedAt,
			&i.UploaderName,
			&i.UploaderUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listIssueAttachments = `-- name: ListIssueAttachments :many
SELECT ia.id, ia.issue_id, ia.comment_id, ia.uploaded_by, ia.original_name, ia.storage_key, ia.resource_type, ia.mime_type, ia.file_size, ia.created_at,
    uploader.fullname AS uploader_name, uploader.username AS uploader_username
FROM issue_attachments ia
JOIN users uploader ON ia.uploaded_by = uploader.id
WHERE ia.issue_id = $1 AND ia.deleted_at IS NULL
ORDER BY ia.created_at ASC
`

type ListIssueAttachmentsRow struct {
	ID               int64              `json:"id"`
	IssueID          int64              `json:"issue_id"`
	CommentID        pgtype.Int8        `json:"comment_id"`
	UploadedBy       int64              `json:"uploaded_by"`
	OriginalName     string             `json:"original_name"`
	StorageKey       string             `json:"storage_key"`
	ResourceType     string             `json:"resource_type"`
	MimeType         string             `json:"mime_type"`
	FileSize         int64              `json:"file_size"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UploaderName     string             `json:"uploader_name"`
	UploaderUsername string             `json:"uploader_username"`
}

func (q *Queries) ListIssueAttachments(ctx context.Context, issueID int64) ([]ListIssueAttachmentsRow, error) {
	rows, err := q.db.Query(ctx, listIssueAttachments, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListIssueAttachmentsRow
	for rows.Next() {
		var i ListIssueAttachmentsRow
		if err := rows.Scan(
			&i.ID,
			&i.IssueID,
			&i.CommentID,
			&i.UploadedBy,
			&i.OriginalName,
			&i.StorageKey,
			&i.ResourceType,
			&i.MimeType,
			&i.FileSize,
			&i.CreatedAt,
			&i.UploaderName,
			&i.UploaderUsername,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAttachment = `-- name: SoftDeleteAttachment :one
UPDATE issue_attachments
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, storage_key, resource_type
`

type SoftDeleteAttachmentRow struct {
	ID           int64  `json:"id"`
	StorageKey   string `json:"storage_key"`
	ResourceType string `json:"resource_type"`
}

func (q *Queries) SoftDeleteAttachment(ctx context.Context, id int64) (SoftDeleteAttachmentRow, error) {
	row := q.db.QueryRow(ctx, softDeleteAttachment, id)
	var i SoftDeleteAttachmentRow
	err := row.Scan(&i.ID, &i.StorageKey, &i.ResourceType)
	return i, err
}
