// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: issues.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createIssue = `-- name: CreateIssue :one
INSERT INTO issues(
    project_id,
    created_by,
    assigned_to,
    title,
    description,
    status,
    priority
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
RETURNING id, project_id, created_by, assigned_to, title, description, status, priority, created_at, updated_at, deleted_at
`

type CreateIssueParams struct {
	ProjectID   int64         `json:"project_id"`
	CreatedBy   int64         `json:"created_by"`
	AssignedTo  pgtype.Int8   `json:"assigned_to"`
	Title       string        `json:"title"`
	Description string        `json:"description"`
	Status      IssueStatus   `json:"status"`
	Priority    IssuePriority `json:"priority"`
}

func (q *Queries) CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error) {
	row := q.db.QueryRow(ctx, createIssue,
		arg.ProjectID,
		arg.CreatedBy,
		arg.AssignedTo,
		arg.Title,
		arg.Description,
		arg.Status,
		arg.Priority,
	)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteIssue = `-- name: DeleteIssue :one
UPDATE issues
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id
`

func (q *Queries) DeleteIssue(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, deleteIssue, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const getIssueByID = `-- name: GetIssueByID :one
SELECT i.id, i.project_id, i.created_by, i.assigned_to, i.title, i.description, i.status, i.priority, i.created_at, i.updated_at, creator.display_name AS creator_name, assignee.display_name AS assignee_name, deleted_at
FROM issues i
JOIN users creator ON i.created_by = creator.id
LEFT JOIN users assignee ON i.assigned_to = assignee.id
WHERE i.id = $1 AND i.deleted_at IS NULL
`

type GetIssueByIDRow struct {
	ID           int64              `json:"id"`
	ProjectID    int64              `json:"project_id"`
	CreatedBy    int64              `json:"created_by"`
	AssignedTo   pgtype.Int8        `json:"assigned_to"`
	Title        string             `json:"title"`
	Description  string             `json:"description"`
	Status       IssueStatus        `json:"status"`
	Priority     IssuePriority      `json:"priority"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
	CreatorName  string             `json:"creator_name"`
	AssigneeName pgtype.Text        `json:"assignee_name"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetIssueByID(ctx context.Context, id int64) (GetIssueByIDRow, error) {
	row := q.db.QueryRow(ctx, getIssueByID, id)
	var i GetIssueByIDRow
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.CreatorName,
		&i.AssigneeName,
		&i.DeletedAt,
	)
	return i, err
}

const getIssueProjectID = `-- name: GetIssueProjectID :one
SELECT project_id
FROM issues
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetIssueProjectID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getIssueProjectID, id)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const listAssignedIssues = `-- name: ListAssignedIssues :many
SELECT i.id, i.project_id, i.title, i.status, i.priority, i.created_at, i.deleted_at, p.name AS project_name
FROM issues i
JOIN projects p ON i.project_id = p.id
WHERE i.assigned_to = $1 AND i.deleted_at IS NULL
ORDER BY i.created_at DESC
`

type ListAssignedIssuesRow struct {
	ID          int64              `json:"id"`
	ProjectID   int64              `json:"project_id"`
	Title       string             `json:"title"`
	Status      IssueStatus        `json:"status"`
	Priority    IssuePriority      `json:"priority"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) ListAssignedIssues(ctx context.Context, assignedTo pgtype.Int8) ([]ListAssignedIssuesRow, error) {
	rows, err := q.db.Query(ctx, listAssignedIssues, assignedTo)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssignedIssuesRow
	for rows.Next() {
		var i ListAssignedIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCreatedIssues = `-- name: ListCreatedIssues :many
SELECT i.id, i.project_id, i.title, i.status, i.priority, i.created_at, i.deleted_at, p.name AS project_name
FROM issues i
JOIN projects p ON i.project_id = p.id
WHERE i.created_by = $1 AND i.deleted_at IS NULL
ORDER BY i.created_at DESC
`

type ListCreatedIssuesRow struct {
	ID          int64              `json:"id"`
	ProjectID   int64              `json:"project_id"`
	Title       string             `json:"title"`
	Status      IssueStatus        `json:"status"`
	Priority    IssuePriority      `json:"priority"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	ProjectName string             `json:"project_name"`
}

func (q *Queries) ListCreatedIssues(ctx context.Context, createdBy int64) ([]ListCreatedIssuesRow, error) {
	rows, err := q.db.Query(ctx, listCreatedIssues, createdBy)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListCreatedIssuesRow
	for rows.Next() {
		var i ListCreatedIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.DeletedAt,
			&i.ProjectName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectIssues = `-- name: ListProjectIssues :many
SELECT i.id, i.project_id, i.title, i.status, i.priority, i.created_at, i.assigned_to, i.created_by, i.deleted_at,
       u_creator.display_name AS creator_name,
       u_assignee.display_name AS assignee_name
FROM issues i
INNER JOIN users u_creator ON i.created_by = u_creator.id
LEFT JOIN users u_assignee ON i.assigned_to = u_assignee.id
WHERE i.project_id = $1 AND i.deleted_at IS NULL
    AND ($2::issue_status IS NULL OR i.status = $2)
    AND ($3::issue_priority IS NULL OR i.priority = $3)
    AND ($4::bigint IS NULL OR i.assigned_to = $4)
    AND ($5::text IS NULL OR i.title ILIKE '%' || $5 || '%')
ORDER BY i.created_at DESC
LIMIT $7
OFFSET $6
`

type ListProjectIssuesParams struct {
	ProjectID  int64             `json:"project_id"`
	Status     NullIssueStatus   `json:"status"`
	Priority   NullIssuePriority `json:"priority"`
	AssignedTo pgtype.Int8       `json:"assigned_to"`
	Search     pgtype.Text       `json:"search"`
	PageOffset int32             `json:"page_offset"`
	PageLimit  int32             `json:"page_limit"`
}

type ListProjectIssuesRow struct {
	ID           int64              `json:"id"`
	ProjectID    int64              `json:"project_id"`
	Title        string             `json:"title"`
	Status       IssueStatus        `json:"status"`
	Priority     IssuePriority      `json:"priority"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	AssignedTo   pgtype.Int8        `json:"assigned_to"`
	CreatedBy    int64              `json:"created_by"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
	CreatorName  string             `json:"creator_name"`
	AssigneeName pgtype.Text        `json:"assignee_name"`
}

func (q *Queries) ListProjectIssues(ctx context.Context, arg ListProjectIssuesParams) ([]ListProjectIssuesRow, error) {
	rows, err := q.db.Query(ctx, listProjectIssues,
		arg.ProjectID,
		arg.Status,
		arg.Priority,
		arg.AssignedTo,
		arg.Search,
		arg.PageOffset,
		arg.PageLimit,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectIssuesRow
	for rows.Next() {
		var i ListProjectIssuesRow
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Title,
			&i.Status,
			&i.Priority,
			&i.CreatedAt,
			&i.AssignedTo,
			&i.CreatedBy,
			&i.DeletedAt,
			&i.CreatorName,
			&i.AssigneeName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const restoreIssue = `-- name: RestoreIssue :one
UPDATE issues
SET deleted_at = NULL
WHERE id = $1 AND deleted_at IS NOT NULL
RETURNING id
`

func (q *Queries) RestoreIssue(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, restoreIssue, id)
	var id_2 int64
	err := row.Scan(&id_2)
	return id_2, err
}

const updateIssueAssignee = `-- name: UpdateIssueAssignee :one
UPDATE issues
SET assigned_to = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, created_by, assigned_to, title, description, status, priority, created_at, updated_at, deleted_at
`

type UpdateIssueAssigneeParams struct {
	ID         int64       `json:"id"`
	AssignedTo pgtype.Int8 `json:"assigned_to"`
}

func (q *Queries) UpdateIssueAssignee(ctx context.Context, arg UpdateIssueAssigneeParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssueAssignee, arg.ID, arg.AssignedTo)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateIssueDetails = `-- name: UpdateIssueDetails :one
UPDATE issues
SET title = $2, description = $3
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, created_by, assigned_to, title, description, status, priority, created_at, updated_at, deleted_at
`

type UpdateIssueDetailsParams struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	Description string `json:"description"`
}

func (q *Queries) UpdateIssueDetails(ctx context.Context, arg UpdateIssueDetailsParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssueDetails, arg.ID, arg.Title, arg.Description)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateIssuePriority = `-- name: UpdateIssuePriority :one
UPDATE issues
SET priority = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, created_by, assigned_to, title, description, status, priority, created_at, updated_at, deleted_at
`

type UpdateIssuePriorityParams struct {
	ID       int64         `json:"id"`
	Priority IssuePriority `json:"priority"`
}

func (q *Queries) UpdateIssuePriority(ctx context.Context, arg UpdateIssuePriorityParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssuePriority, arg.ID, arg.Priority)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateIssueStatus = `-- name: UpdateIssueStatus :one
UPDATE issues
SET status = $2
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id, created_by, assigned_to, title, description, status, priority, created_at, updated_at, deleted_at
`

type UpdateIssueStatusParams struct {
	ID     int64       `json:"id"`
	Status IssueStatus `json:"status"`
}

func (q *Queries) UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) (Issue, error) {
	row := q.db.QueryRow(ctx, updateIssueStatus, arg.ID, arg.Status)
	var i Issue
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.CreatedBy,
		&i.AssignedTo,
		&i.Title,
		&i.Description,
		&i.Status,
		&i.Priority,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
