// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: labels.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const attachLabelsToIssue = `-- name: AttachLabelsToIssue :exec
INSERT INTO issue_labels(
    issue_id,
    label_id
) SELECT $1, unnest($2::bigint[])
ON CONFLICT (issue_id, label_id) DO NOTHING
`

type AttachLabelsToIssueParams struct {
	IssueID int64   `json:"issue_id"`
	LabelID []int64 `json:"label_id"`
}

func (q *Queries) AttachLabelsToIssue(ctx context.Context, arg AttachLabelsToIssueParams) error {
	_, err := q.db.Exec(ctx, attachLabelsToIssue, arg.IssueID, arg.LabelID)
	return err
}

const countProjectLabels = `-- name: CountProjectLabels :one
SELECT COUNT(*) 
FROM labels
WHERE project_id = $1
AND id = ANY($2::bigint[])
AND deleted_at IS NULL
`

type CountProjectLabelsParams struct {
	ProjectID int64   `json:"project_id"`
	LabelIds  []int64 `json:"label_ids"`
}

func (q *Queries) CountProjectLabels(ctx context.Context, arg CountProjectLabelsParams) (int64, error) {
	row := q.db.QueryRow(ctx, countProjectLabels, arg.ProjectID, arg.LabelIds)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const createLabel = `-- name: CreateLabel :one
INSERT INTO labels(
    project_id,
    name,
    color,
    created_by
) VALUES (
    $1,$2,$3,$4
)
RETURNING id, project_id, name, color, created_by, created_at, updated_at, deleted_at
`

type CreateLabelParams struct {
	ProjectID int64  `json:"project_id"`
	Name      string `json:"name"`
	Color     string `json:"color"`
	CreatedBy int64  `json:"created_by"`
}

func (q *Queries) CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, createLabel,
		arg.ProjectID,
		arg.Name,
		arg.Color,
		arg.CreatedBy,
	)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteLabel = `-- name: DeleteLabel :one
UPDATE labels
SET deleted_at = NOW()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, project_id
`

type DeleteLabelRow struct {
	ID        int64 `json:"id"`
	ProjectID int64 `json:"project_id"`
}

func (q *Queries) DeleteLabel(ctx context.Context, id int64) (DeleteLabelRow, error) {
	row := q.db.QueryRow(ctx, deleteLabel, id)
	var i DeleteLabelRow
	err := row.Scan(&i.ID, &i.ProjectID)
	return i, err
}

const getLabelByID = `-- name: GetLabelByID :one
SELECT id, project_id, name, color, created_by, created_at, updated_at, deleted_at
FROM labels
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetLabelByID(ctx context.Context, id int64) (Label, error) {
	row := q.db.QueryRow(ctx, getLabelByID, id)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLabelProjectID = `-- name: GetLabelProjectID :one
SELECT project_id
FROM labels
WHERE id = $1
AND deleted_at IS NULL
`

func (q *Queries) GetLabelProjectID(ctx context.Context, id int64) (int64, error) {
	row := q.db.QueryRow(ctx, getLabelProjectID, id)
	var project_id int64
	err := row.Scan(&project_id)
	return project_id, err
}

const listIssueLabels = `-- name: ListIssueLabels :many
SELECT l.id, l.project_id, l.name, l.color, l.created_by, l.created_at, l.updated_at, l.deleted_at
FROM issue_labels il
JOIN labels l ON il.label_id = l.id
WHERE il.issue_id = $1
AND l.deleted_at IS NULL
ORDER BY l.name
`

func (q *Queries) ListIssueLabels(ctx context.Context, issueID int64) ([]Label, error) {
	rows, err := q.db.Query(ctx, listIssueLabels, issueID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectLabels = `-- name: ListProjectLabels :many
SELECT id, project_id, name, color, created_by, created_at, updated_at, deleted_at
FROM labels
WHERE project_id = $1 AND deleted_at IS NULL
ORDER BY name ASC
`

func (q *Queries) ListProjectLabels(ctx context.Context, projectID int64) ([]Label, error) {
	rows, err := q.db.Query(ctx, listProjectLabels, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Label
	for rows.Next() {
		var i Label
		if err := rows.Scan(
			&i.ID,
			&i.ProjectID,
			&i.Name,
			&i.Color,
			&i.CreatedBy,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const removeLabelFromIssue = `-- name: RemoveLabelFromIssue :one
DELETE FROM issue_labels
WHERE issue_id = $1
AND label_id = $2
RETURNING issue_id
`

type RemoveLabelFromIssueParams struct {
	IssueID int64 `json:"issue_id"`
	LabelID int64 `json:"label_id"`
}

func (q *Queries) RemoveLabelFromIssue(ctx context.Context, arg RemoveLabelFromIssueParams) (int64, error) {
	row := q.db.QueryRow(ctx, removeLabelFromIssue, arg.IssueID, arg.LabelID)
	var issue_id int64
	err := row.Scan(&issue_id)
	return issue_id, err
}

const updateLabel = `-- name: UpdateLabel :one
UPDATE labels
SET name = COALESCE($1, name), 
    color = COALESCE($2, color)
WHERE id = $3 AND deleted_at IS NULL
RETURNING id, project_id, name, color, created_by, created_at, updated_at, deleted_at
`

type UpdateLabelParams struct {
	Name  pgtype.Text `json:"name"`
	Color pgtype.Text `json:"color"`
	ID    int64       `json:"id"`
}

func (q *Queries) UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error) {
	row := q.db.QueryRow(ctx, updateLabel, arg.Name, arg.Color, arg.ID)
	var i Label
	err := row.Scan(
		&i.ID,
		&i.ProjectID,
		&i.Name,
		&i.Color,
		&i.CreatedBy,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
