// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/jackc/pgx/v5/pgtype"
)

type ActivityType string

const (
	ActivityTypeISSUECREATED         ActivityType = "ISSUE_CREATED"
	ActivityTypeISSUEDETAILSUPDATED  ActivityType = "ISSUE_DETAILS_UPDATED"
	ActivityTypeISSUESTATUSCHANGED   ActivityType = "ISSUE_STATUS_CHANGED"
	ActivityTypeISSUEPRIORITYCHANGED ActivityType = "ISSUE_PRIORITY_CHANGED"
	ActivityTypeISSUEASSIGNEECHANGED ActivityType = "ISSUE_ASSIGNEE_CHANGED"
	ActivityTypeISSUEDELETED         ActivityType = "ISSUE_DELETED"
	ActivityTypeISSUERESTORED        ActivityType = "ISSUE_RESTORED"
	ActivityTypeCOMMENTCREATED       ActivityType = "COMMENT_CREATED"
	ActivityTypeCOMMENTUPDATED       ActivityType = "COMMENT_UPDATED"
	ActivityTypeCOMMENTDELETED       ActivityType = "COMMENT_DELETED"
	ActivityTypeDUEDATECHANGED       ActivityType = "DUE_DATE_CHANGED"
)

func (e *ActivityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ActivityType(s)
	case string:
		*e = ActivityType(s)
	default:
		return fmt.Errorf("unsupported scan type for ActivityType: %T", src)
	}
	return nil
}

type NullActivityType struct {
	ActivityType ActivityType `json:"activity_type"`
	Valid        bool         `json:"valid"` // Valid is true if ActivityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullActivityType) Scan(value interface{}) error {
	if value == nil {
		ns.ActivityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ActivityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullActivityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ActivityType), nil
}

type IssuePriority string

const (
	IssuePriorityLOW    IssuePriority = "LOW"
	IssuePriorityMEDIUM IssuePriority = "MEDIUM"
	IssuePriorityHIGH   IssuePriority = "HIGH"
)

func (e *IssuePriority) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssuePriority(s)
	case string:
		*e = IssuePriority(s)
	default:
		return fmt.Errorf("unsupported scan type for IssuePriority: %T", src)
	}
	return nil
}

type NullIssuePriority struct {
	IssuePriority IssuePriority `json:"issue_priority"`
	Valid         bool          `json:"valid"` // Valid is true if IssuePriority is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssuePriority) Scan(value interface{}) error {
	if value == nil {
		ns.IssuePriority, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssuePriority.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssuePriority) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssuePriority), nil
}

type IssueStatus string

const (
	IssueStatusTODO       IssueStatus = "TODO"
	IssueStatusINPROGRESS IssueStatus = "IN_PROGRESS"
	IssueStatusDONE       IssueStatus = "DONE"
)

func (e *IssueStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IssueStatus(s)
	case string:
		*e = IssueStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for IssueStatus: %T", src)
	}
	return nil
}

type NullIssueStatus struct {
	IssueStatus IssueStatus `json:"issue_status"`
	Valid       bool        `json:"valid"` // Valid is true if IssueStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIssueStatus) Scan(value interface{}) error {
	if value == nil {
		ns.IssueStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IssueStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIssueStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IssueStatus), nil
}

type UserRole string

const (
	UserRoleADMIN  UserRole = "ADMIN"
	UserRoleMEMBER UserRole = "MEMBER"
)

func (e *UserRole) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = UserRole(s)
	case string:
		*e = UserRole(s)
	default:
		return fmt.Errorf("unsupported scan type for UserRole: %T", src)
	}
	return nil
}

type NullUserRole struct {
	UserRole UserRole `json:"user_role"`
	Valid    bool     `json:"valid"` // Valid is true if UserRole is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullUserRole) Scan(value interface{}) error {
	if value == nil {
		ns.UserRole, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.UserRole.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullUserRole) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.UserRole), nil
}

type Comment struct {
	ID              int64              `json:"id"`
	IssueID         int64              `json:"issue_id"`
	AuthorID        int64              `json:"author_id"`
	ParentCommentID pgtype.Int8        `json:"parent_comment_id"`
	Content         string             `json:"content"`
	IsEdited        bool               `json:"is_edited"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
}

type Issue struct {
	ID          int64              `json:"id"`
	ProjectID   int64              `json:"project_id"`
	CreatedBy   int64              `json:"created_by"`
	AssignedTo  pgtype.Int8        `json:"assigned_to"`
	Title       string             `json:"title"`
	Description string             `json:"description"`
	Status      IssueStatus        `json:"status"`
	Priority    IssuePriority      `json:"priority"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
	DueDate     pgtype.Timestamptz `json:"due_date"`
}

type IssueActivity struct {
	ID           int64              `json:"id"`
	IssueID      int64              `json:"issue_id"`
	ActorID      int64              `json:"actor_id"`
	ActivityType ActivityType       `json:"activity_type"`
	FieldName    pgtype.Text        `json:"field_name"`
	OldValue     pgtype.Text        `json:"old_value"`
	NewValue     pgtype.Text        `json:"new_value"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
}

type IssueAttachment struct {
	ID           int64              `json:"id"`
	IssueID      int64              `json:"issue_id"`
	CommentID    pgtype.Int8        `json:"comment_id"`
	UploadedBy   int64              `json:"uploaded_by"`
	OriginalName string             `json:"original_name"`
	StorageKey   string             `json:"storage_key"`
	ResourceType string             `json:"resource_type"`
	MimeType     string             `json:"mime_type"`
	FileSize     int64              `json:"file_size"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	DeletedAt    pgtype.Timestamptz `json:"deleted_at"`
}

type IssueLabel struct {
	IssueID   int64              `json:"issue_id"`
	LabelID   int64              `json:"label_id"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

type Label struct {
	ID        int64              `json:"id"`
	ProjectID int64              `json:"project_id"`
	Name      string             `json:"name"`
	Color     string             `json:"color"`
	CreatedBy int64              `json:"created_by"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
	DeletedAt pgtype.Timestamptz `json:"deleted_at"`
}

type Project struct {
	ID          int64              `json:"id"`
	WorkspaceID int64              `json:"workspace_id"`
	LeadID      int64              `json:"lead_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type ProjectMember struct {
	ProjectID int64              `json:"project_id"`
	UserID    int64              `json:"user_id"`
	JoinedAt  pgtype.Timestamptz `json:"joined_at"`
}

type User struct {
	ID           int64              `json:"id"`
	Fullname     string             `json:"fullname"`
	DisplayName  string             `json:"display_name"`
	Email        string             `json:"email"`
	PasswordHash string             `json:"password_hash"`
	CreatedAt    pgtype.Timestamptz `json:"created_at"`
	UpdatedAt    pgtype.Timestamptz `json:"updated_at"`
}

type Workspace struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
	UpdatedAt pgtype.Timestamptz `json:"updated_at"`
}

type WorkspaceMember struct {
	WorkspaceID int64              `json:"workspace_id"`
	UserID      int64              `json:"user_id"`
	Role        UserRole           `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
}
