// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects(
    owner_id,
    name,
    description
)
VALUES(
    $1, $2, $3
)
RETURNING id, owner_id, name, description, created_at, updated_at
`

type CreateProjectParams struct {
	OwnerID     int64  `json:"owner_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error) {
	row := q.db.QueryRow(ctx, createProject, arg.OwnerID, arg.Name, arg.Description)
	var i Project
	err := row.Scan(
		&i.ID,
		&i.OwnerID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
