// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: projects.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createProject = `-- name: CreateProject :one
INSERT INTO projects(
    workspace_id,
    lead_id,
    name,
    description
)
VALUES(
    $1, $2, $3, $4
)
RETURNING id, workspace_id, lead_id, name, description, created_at
`

type CreateProjectParams struct {
	WorkspaceID int64  `json:"workspace_id"`
	LeadID      int64  `json:"lead_id"`
	Name        string `json:"name"`
	Description string `json:"description"`
}

type CreateProjectRow struct {
	ID          int64              `json:"id"`
	WorkspaceID int64              `json:"workspace_id"`
	LeadID      int64              `json:"lead_id"`
	Name        string             `json:"name"`
	Description string             `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error) {
	row := q.db.QueryRow(ctx, createProject,
		arg.WorkspaceID,
		arg.LeadID,
		arg.Name,
		arg.Description,
	)
	var i CreateProjectRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.LeadID,
		&i.Name,
		&i.Description,
		&i.CreatedAt,
	)
	return i, err
}

const isProjectLead = `-- name: IsProjectLead :one
SELECT EXISTS (
    SELECT 1
    FROM projects
    WHERE id = $1 AND lead_id = $2
)
`

type IsProjectLeadParams struct {
	ID     int64 `json:"id"`
	LeadID int64 `json:"lead_id"`
}

func (q *Queries) IsProjectLead(ctx context.Context, arg IsProjectLeadParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProjectLead, arg.ID, arg.LeadID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listProjectsByLead = `-- name: ListProjectsByLead :many
SELECT id, workspace_id, lead_id, name, description, created_at, updated_at
FROM projects
WHERE lead_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByLead(ctx context.Context, leadID int64) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByLead, leadID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.LeadID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listProjectsByWorkspace = `-- name: ListProjectsByWorkspace :many
SELECT id, workspace_id, lead_id, name, description, created_at, updated_at
FROM projects
WHERE workspace_id = $1
ORDER BY created_at DESC
`

func (q *Queries) ListProjectsByWorkspace(ctx context.Context, workspaceID int64) ([]Project, error) {
	rows, err := q.db.Query(ctx, listProjectsByWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Project
	for rows.Next() {
		var i Project
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.LeadID,
			&i.Name,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
