// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: project_members.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addMemberToProject = `-- name: AddMemberToProject :one
INSERT INTO project_members(
    project_id,
    user_id
)
VALUES(
    $1, $2
)
RETURNING project_id, user_id, joined_at
`

type AddMemberToProjectParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) AddMemberToProject(ctx context.Context, arg AddMemberToProjectParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, addMemberToProject, arg.ProjectID, arg.UserID)
	var i ProjectMember
	err := row.Scan(&i.ProjectID, &i.UserID, &i.JoinedAt)
	return i, err
}

const isProjectMember = `-- name: IsProjectMember :one
SELECT EXISTS (
    SELECT 1
    FROM project_members
    WHERE project_id = $1 AND user_id = $2
)
`

type IsProjectMemberParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
}

func (q *Queries) IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error) {
	row := q.db.QueryRow(ctx, isProjectMember, arg.ProjectID, arg.UserID)
	var exists bool
	err := row.Scan(&exists)
	return exists, err
}

const listProjectMembers = `-- name: ListProjectMembers :many
SELECT u.id, u.email, u.fullname, u.fullname, u.username, pm.joined_at
FROM project_members pm
JOIN users u ON pm.user_id = u.id
WHERE pm.project_id = $1
ORDER BY pm.joined_at ASC
`

type ListProjectMembersRow struct {
	ID         int64              `json:"id"`
	Email      string             `json:"email"`
	Fullname   string             `json:"fullname"`
	Fullname_2 string             `json:"fullname_2"`
	Username   string             `json:"username"`
	JoinedAt   pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListProjectMembers(ctx context.Context, projectID int64) ([]ListProjectMembersRow, error) {
	rows, err := q.db.Query(ctx, listProjectMembers, projectID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListProjectMembersRow
	for rows.Next() {
		var i ListProjectMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Email,
			&i.Fullname,
			&i.Fullname_2,
			&i.Username,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const safeAddMemberToProject = `-- name: SafeAddMemberToProject :one
INSERT INTO project_members (
    project_id, 
    user_id
)
SELECT $1, $2
WHERE EXISTS(
    SELECT 1 FROM projects p
    WHERE p.id =  $1 AND p.lead_id = $3
)
AND EXISTS(
    SELECT 1 FROM workspace_members wm
    WHERE wm.user_id = $2
    AND wm.workspace_id = (
        SELECT workspace_id
        FROM projects
        WHERE id = $1
    )
)
RETURNING project_id, user_id, joined_at
`

type SafeAddMemberToProjectParams struct {
	ProjectID int64 `json:"project_id"`
	UserID    int64 `json:"user_id"`
	LeadID    int64 `json:"lead_id"`
}

func (q *Queries) SafeAddMemberToProject(ctx context.Context, arg SafeAddMemberToProjectParams) (ProjectMember, error) {
	row := q.db.QueryRow(ctx, safeAddMemberToProject, arg.ProjectID, arg.UserID, arg.LeadID)
	var i ProjectMember
	err := row.Scan(&i.ProjectID, &i.UserID, &i.JoinedAt)
	return i, err
}
