// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

type Querier interface {
	AddMemberToProject(ctx context.Context, arg AddMemberToProjectParams) (ProjectMember, error)
	AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error)
	AttachLabelsToIssue(ctx context.Context, arg AttachLabelsToIssueParams) error
	CountProjectLabels(ctx context.Context, arg CountProjectLabelsParams) (int64, error)
	CreateActivity(ctx context.Context, arg CreateActivityParams) (IssueActivity, error)
	CreateAttachment(ctx context.Context, arg CreateAttachmentParams) (IssueAttachment, error)
	CreateComment(ctx context.Context, arg CreateCommentParams) (Comment, error)
	CreateIssue(ctx context.Context, arg CreateIssueParams) (Issue, error)
	CreateLabel(ctx context.Context, arg CreateLabelParams) (Label, error)
	CreateOnboardingUser(ctx context.Context, arg CreateOnboardingUserParams) (CreateOnboardingUserRow, error)
	CreateProject(ctx context.Context, arg CreateProjectParams) (CreateProjectRow, error)
	CreateWorkspace(ctx context.Context, name string) (Workspace, error)
	DeleteComment(ctx context.Context, id int64) (int64, error)
	DeleteIssue(ctx context.Context, id int64) (int64, error)
	DeleteLabel(ctx context.Context, id int64) (DeleteLabelRow, error)
	GetAttachmentByID(ctx context.Context, id int64) (GetAttachmentByIDRow, error)
	GetCommentByID(ctx context.Context, id int64) (GetCommentByIDRow, error)
	GetIssueByID(ctx context.Context, id int64) (GetIssueByIDRow, error)
	GetIssueProjectID(ctx context.Context, id int64) (int64, error)
	GetLabelByID(ctx context.Context, id int64) (Label, error)
	GetLabelProjectID(ctx context.Context, id int64) (int64, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error)
	GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error)
	GetWorkspaceByName(ctx context.Context, name string) (Workspace, error)
	GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error)
	IsProjectLead(ctx context.Context, arg IsProjectLeadParams) (bool, error)
	IsProjectMember(ctx context.Context, arg IsProjectMemberParams) (bool, error)
	IsWorkspaceMember(ctx context.Context, arg IsWorkspaceMemberParams) (UserRole, error)
	ListAssignedIssues(ctx context.Context, assignedTo pgtype.Int8) ([]ListAssignedIssuesRow, error)
	ListCommentAttachments(ctx context.Context, commentID pgtype.Int8) ([]ListCommentAttachmentsRow, error)
	ListCreatedIssues(ctx context.Context, createdBy int64) ([]ListCreatedIssuesRow, error)
	ListIssueActivities(ctx context.Context, arg ListIssueActivitiesParams) ([]ListIssueActivitiesRow, error)
	ListIssueAttachments(ctx context.Context, issueID int64) ([]ListIssueAttachmentsRow, error)
	ListIssueComments(ctx context.Context, arg ListIssueCommentsParams) ([]ListIssueCommentsRow, error)
	ListIssueLabels(ctx context.Context, issueID int64) ([]Label, error)
	ListProjectIssues(ctx context.Context, arg ListProjectIssuesParams) ([]ListProjectIssuesRow, error)
	ListProjectLabels(ctx context.Context, projectID int64) ([]Label, error)
	ListProjectMembers(ctx context.Context, projectID int64) ([]ListProjectMembersRow, error)
	ListProjectsByLead(ctx context.Context, leadID int64) ([]Project, error)
	ListProjectsByWorkspace(ctx context.Context, workspaceID int64) ([]Project, error)
	ListUserWorkspaces(ctx context.Context, arg ListUserWorkspacesParams) ([]ListUserWorkspacesRow, error)
	ListWorkspaceMembers(ctx context.Context, workspaceID int64) ([]ListWorkspaceMembersRow, error)
	RemoveLabelFromIssue(ctx context.Context, arg RemoveLabelFromIssueParams) error
	RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) (RemoveWorkspaceMemberRow, error)
	RestoreIssue(ctx context.Context, id int64) (int64, error)
	SafeAddMemberToProject(ctx context.Context, arg SafeAddMemberToProjectParams) (ProjectMember, error)
	SoftDeleteAttachment(ctx context.Context, id int64) (SoftDeleteAttachmentRow, error)
	UpdateComment(ctx context.Context, arg UpdateCommentParams) (Comment, error)
	UpdateIssueAssignee(ctx context.Context, arg UpdateIssueAssigneeParams) (Issue, error)
	UpdateIssueDetails(ctx context.Context, arg UpdateIssueDetailsParams) (Issue, error)
	UpdateIssueDueDate(ctx context.Context, arg UpdateIssueDueDateParams) (Issue, error)
	UpdateIssuePriority(ctx context.Context, arg UpdateIssuePriorityParams) (Issue, error)
	UpdateIssueStatus(ctx context.Context, arg UpdateIssueStatusParams) (Issue, error)
	UpdateLabel(ctx context.Context, arg UpdateLabelParams) (Label, error)
}

var _ Querier = (*Queries)(nil)
