// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"
)

type Querier interface {
	CreateProject(ctx context.Context, arg CreateProjectParams) (Project, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (User, error)
	GetUserByEmail(ctx context.Context, email string) (GetUserByEmailRow, error)
	GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error)
	GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error)
	ListProjectsByOwner(ctx context.Context, ownerID int64) ([]Project, error)
}

var _ Querier = (*Queries)(nil)
