// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: users.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const createOnboardingUser = `-- name: CreateOnboardingUser :one
INSERT INTO users(
    email,
    fullname,
    display_name,
    password_hash
)
VALUES(
    $1, $2, $3, $4
)
RETURNING id, email, fullname, display_name, created_at
`

type CreateOnboardingUserParams struct {
	Email        string `json:"email"`
	Fullname     string `json:"fullname"`
	DisplayName  string `json:"display_name"`
	PasswordHash string `json:"password_hash"`
}

type CreateOnboardingUserRow struct {
	ID          int64              `json:"id"`
	Email       string             `json:"email"`
	Fullname    string             `json:"fullname"`
	DisplayName string             `json:"display_name"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) CreateOnboardingUser(ctx context.Context, arg CreateOnboardingUserParams) (CreateOnboardingUserRow, error) {
	row := q.db.QueryRow(ctx, createOnboardingUser,
		arg.Email,
		arg.Fullname,
		arg.DisplayName,
		arg.PasswordHash,
	)
	var i CreateOnboardingUserRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.Fullname,
		&i.DisplayName,
		&i.CreatedAt,
	)
	return i, err
}

const getUserByID = `-- name: GetUserByID :one
SELECT id, display_name, fullname, email, created_at, updated_at
FROM users
WHERE id=$1
LIMIT 1
`

type GetUserByIDRow struct {
	ID          int64              `json:"id"`
	DisplayName string             `json:"display_name"`
	Fullname    string             `json:"fullname"`
	Email       string             `json:"email"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) GetUserByID(ctx context.Context, id int64) (GetUserByIDRow, error) {
	row := q.db.QueryRow(ctx, getUserByID, id)
	var i GetUserByIDRow
	err := row.Scan(
		&i.ID,
		&i.DisplayName,
		&i.Fullname,
		&i.Email,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getUserForLogin = `-- name: GetUserForLogin :one
SELECT id, email, display_name, fullname, password_hash
FROM users
WHERE email = $1
LIMIT 1
`

type GetUserForLoginRow struct {
	ID           int64  `json:"id"`
	Email        string `json:"email"`
	DisplayName  string `json:"display_name"`
	Fullname     string `json:"fullname"`
	PasswordHash string `json:"password_hash"`
}

func (q *Queries) GetUserForLogin(ctx context.Context, email string) (GetUserForLoginRow, error) {
	row := q.db.QueryRow(ctx, getUserForLogin, email)
	var i GetUserForLoginRow
	err := row.Scan(
		&i.ID,
		&i.Email,
		&i.DisplayName,
		&i.Fullname,
		&i.PasswordHash,
	)
	return i, err
}
