// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_invitations.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const acceptInvitation = `-- name: AcceptInvitation :one
UPDATE workspace_invitations
SET status = 'ACCEPTED', responded_at = NOW()
WHERE id = $1 AND invited_user_id = $2 AND status = 'PENDING'
RETURNING id, workspace_id, invited_user_id, status, responded_at
`

type AcceptInvitationParams struct {
	ID            int64 `json:"id"`
	InvitedUserID int64 `json:"invited_user_id"`
}

type AcceptInvitationRow struct {
	ID            int64              `json:"id"`
	WorkspaceID   int64              `json:"workspace_id"`
	InvitedUserID int64              `json:"invited_user_id"`
	Status        string             `json:"status"`
	RespondedAt   pgtype.Timestamptz `json:"responded_at"`
}

func (q *Queries) AcceptInvitation(ctx context.Context, arg AcceptInvitationParams) (AcceptInvitationRow, error) {
	row := q.db.QueryRow(ctx, acceptInvitation, arg.ID, arg.InvitedUserID)
	var i AcceptInvitationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InvitedUserID,
		&i.Status,
		&i.RespondedAt,
	)
	return i, err
}

const cancelInvitation = `-- name: CancelInvitation :one
UPDATE workspace_invitations
SET status = 'CANCELLED', responded_at = NOW()
WHERE id = $1 AND invited_by = $2 AND status = 'PENDING'
RETURNING id, status, responded_at
`

type CancelInvitationParams struct {
	ID        int64 `json:"id"`
	InvitedBy int64 `json:"invited_by"`
}

type CancelInvitationRow struct {
	ID          int64              `json:"id"`
	Status      string             `json:"status"`
	RespondedAt pgtype.Timestamptz `json:"responded_at"`
}

func (q *Queries) CancelInvitation(ctx context.Context, arg CancelInvitationParams) (CancelInvitationRow, error) {
	row := q.db.QueryRow(ctx, cancelInvitation, arg.ID, arg.InvitedBy)
	var i CancelInvitationRow
	err := row.Scan(&i.ID, &i.Status, &i.RespondedAt)
	return i, err
}

const createWorkspaceInvitation = `-- name: CreateWorkspaceInvitation :one
INSERT INTO workspace_invitations(
    workspace_id, invited_user_id, invited_by
) VALUES (
    $1, $2, $3
)
RETURNING id, workspace_id, invited_user_id, invited_by, status, created_at, responded_at
`

type CreateWorkspaceInvitationParams struct {
	WorkspaceID   int64 `json:"workspace_id"`
	InvitedUserID int64 `json:"invited_user_id"`
	InvitedBy     int64 `json:"invited_by"`
}

func (q *Queries) CreateWorkspaceInvitation(ctx context.Context, arg CreateWorkspaceInvitationParams) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, createWorkspaceInvitation, arg.WorkspaceID, arg.InvitedUserID, arg.InvitedBy)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InvitedUserID,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const declineInvitation = `-- name: DeclineInvitation :one
UPDATE workspace_invitations
SET status = 'DECLINED', responded_at = NOW()
WHERE id = $1 AND invited_user_id = $2 AND status = 'PENDING'
RETURNING id, workspace_id, invited_user_id, status, responded_at
`

type DeclineInvitationParams struct {
	ID            int64 `json:"id"`
	InvitedUserID int64 `json:"invited_user_id"`
}

type DeclineInvitationRow struct {
	ID            int64              `json:"id"`
	WorkspaceID   int64              `json:"workspace_id"`
	InvitedUserID int64              `json:"invited_user_id"`
	Status        string             `json:"status"`
	RespondedAt   pgtype.Timestamptz `json:"responded_at"`
}

func (q *Queries) DeclineInvitation(ctx context.Context, arg DeclineInvitationParams) (DeclineInvitationRow, error) {
	row := q.db.QueryRow(ctx, declineInvitation, arg.ID, arg.InvitedUserID)
	var i DeclineInvitationRow
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InvitedUserID,
		&i.Status,
		&i.RespondedAt,
	)
	return i, err
}

const getWorkspaceInvitation = `-- name: GetWorkspaceInvitation :one
SELECT wi.id, wi.workspace_id, wi.invited_user_id, wi.invited_by, wi.status, wi.created_at, wi.responded_at
FROM workspace_invitations wi
JOIN workspaces w ON wi.workspace_id = w.id
WHERE wi.id = $1 AND w.deleted_at IS NULL
`

func (q *Queries) GetWorkspaceInvitation(ctx context.Context, id int64) (WorkspaceInvitation, error) {
	row := q.db.QueryRow(ctx, getWorkspaceInvitation, id)
	var i WorkspaceInvitation
	err := row.Scan(
		&i.ID,
		&i.WorkspaceID,
		&i.InvitedUserID,
		&i.InvitedBy,
		&i.Status,
		&i.CreatedAt,
		&i.RespondedAt,
	)
	return i, err
}

const listPendingWorkspaceInvitations = `-- name: ListPendingWorkspaceInvitations :many
SELECT wi.id, wi.workspace_id, wi.invited_user_id, wi.invited_by, wi.status, wi.created_at,
    inviter.username AS inviter_username, inviter.fullname AS inviter_fullname,
    w.name AS workspace_name
FROM workspace_invitations wi
JOIN users inviter ON wi.invited_by = inviter.id
JOIN workspaces w ON w.id = wi.workspace_id
WHERE wi.invited_user_id = $1 AND wi.status = 'PENDING' AND w.deleted_at IS NULL
ORDER BY wi.created_at DESC
`

type ListPendingWorkspaceInvitationsRow struct {
	ID              int64              `json:"id"`
	WorkspaceID     int64              `json:"workspace_id"`
	InvitedUserID   int64              `json:"invited_user_id"`
	InvitedBy       int64              `json:"invited_by"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	InviterUsername string             `json:"inviter_username"`
	InviterFullname string             `json:"inviter_fullname"`
	WorkspaceName   string             `json:"workspace_name"`
}

func (q *Queries) ListPendingWorkspaceInvitations(ctx context.Context, invitedUserID int64) ([]ListPendingWorkspaceInvitationsRow, error) {
	rows, err := q.db.Query(ctx, listPendingWorkspaceInvitations, invitedUserID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingWorkspaceInvitationsRow
	for rows.Next() {
		var i ListPendingWorkspaceInvitationsRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InvitedUserID,
			&i.InvitedBy,
			&i.Status,
			&i.CreatedAt,
			&i.InviterUsername,
			&i.InviterFullname,
			&i.WorkspaceName,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPendingWorkspaceInvitationsForWorkspace = `-- name: ListPendingWorkspaceInvitationsForWorkspace :many
SELECT wi.id, wi.workspace_id, wi.invited_user_id, wi.invited_by, wi.status, wi.created_at,
    u.username AS invited_username, u.fullname AS invited_fullname
FROM workspace_invitations wi
JOIN users u ON wi.invited_user_id = u.id
JOIN workspaces w ON wi.workspace_id = w.id
WHERE wi.workspace_id = $1 AND wi.status = 'PENDING' AND w.deleted_at IS NULL
ORDER BY wi.created_at DESC
`

type ListPendingWorkspaceInvitationsForWorkspaceRow struct {
	ID              int64              `json:"id"`
	WorkspaceID     int64              `json:"workspace_id"`
	InvitedUserID   int64              `json:"invited_user_id"`
	InvitedBy       int64              `json:"invited_by"`
	Status          string             `json:"status"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	InvitedUsername string             `json:"invited_username"`
	InvitedFullname string             `json:"invited_fullname"`
}

func (q *Queries) ListPendingWorkspaceInvitationsForWorkspace(ctx context.Context, workspaceID int64) ([]ListPendingWorkspaceInvitationsForWorkspaceRow, error) {
	rows, err := q.db.Query(ctx, listPendingWorkspaceInvitationsForWorkspace, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPendingWorkspaceInvitationsForWorkspaceRow
	for rows.Next() {
		var i ListPendingWorkspaceInvitationsForWorkspaceRow
		if err := rows.Scan(
			&i.ID,
			&i.WorkspaceID,
			&i.InvitedUserID,
			&i.InvitedBy,
			&i.Status,
			&i.CreatedAt,
			&i.InvitedUsername,
			&i.InvitedFullname,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
