// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspace_members.sql

package sqlc

import (
	"context"

	"github.com/jackc/pgx/v5/pgtype"
)

const addWorkspaceMember = `-- name: AddWorkspaceMember :one
INSERT INTO workspace_members(
    workspace_id,
    user_id,
    role
)
VALUES(
    $1, $2, $3
)
RETURNING workspace_id, user_id, role, joined_at
`

type AddWorkspaceMemberParams struct {
	WorkspaceID int64    `json:"workspace_id"`
	UserID      int64    `json:"user_id"`
	Role        UserRole `json:"role"`
}

func (q *Queries) AddWorkspaceMember(ctx context.Context, arg AddWorkspaceMemberParams) (WorkspaceMember, error) {
	row := q.db.QueryRow(ctx, addWorkspaceMember, arg.WorkspaceID, arg.UserID, arg.Role)
	var i WorkspaceMember
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
	)
	return i, err
}

const getWorkspaceMember = `-- name: GetWorkspaceMember :one
SELECT wm.workspace_id, wm.user_id, wm.role, wm.joined_at, u.email, u.fullname, u.username
FROM workspace_members wm
JOIN users u ON wm.user_id = u.id
JOIN workspaces w ON wm.workspace_id = w.id
WHERE wm.workspace_id = $1
AND wm.user_id = $2
AND w.deleted_at IS NULL
`

type GetWorkspaceMemberParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	UserID      int64 `json:"user_id"`
}

type GetWorkspaceMemberRow struct {
	WorkspaceID int64              `json:"workspace_id"`
	UserID      int64              `json:"user_id"`
	Role        UserRole           `json:"role"`
	JoinedAt    pgtype.Timestamptz `json:"joined_at"`
	Email       string             `json:"email"`
	Fullname    string             `json:"fullname"`
	Username    string             `json:"username"`
}

func (q *Queries) GetWorkspaceMember(ctx context.Context, arg GetWorkspaceMemberParams) (GetWorkspaceMemberRow, error) {
	row := q.db.QueryRow(ctx, getWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i GetWorkspaceMemberRow
	err := row.Scan(
		&i.WorkspaceID,
		&i.UserID,
		&i.Role,
		&i.JoinedAt,
		&i.Email,
		&i.Fullname,
		&i.Username,
	)
	return i, err
}

const isWorkspaceAdminIncludingDeleted = `-- name: IsWorkspaceAdminIncludingDeleted :one
SELECT wm.role
FROM workspace_members wm
WHERE wm.workspace_id = $1
AND wm.user_id = $2
`

type IsWorkspaceAdminIncludingDeletedParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) IsWorkspaceAdminIncludingDeleted(ctx context.Context, arg IsWorkspaceAdminIncludingDeletedParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, isWorkspaceAdminIncludingDeleted, arg.WorkspaceID, arg.UserID)
	var role UserRole
	err := row.Scan(&role)
	return role, err
}

const isWorkspaceMember = `-- name: IsWorkspaceMember :one
SELECT wm.role
FROM workspace_members wm
JOIN workspaces w ON wm.workspace_id = w.id
WHERE wm.workspace_id = $1
AND wm.user_id = $2
AND w.deleted_at IS NULL
`

type IsWorkspaceMemberParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) IsWorkspaceMember(ctx context.Context, arg IsWorkspaceMemberParams) (UserRole, error) {
	row := q.db.QueryRow(ctx, isWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var role UserRole
	err := row.Scan(&role)
	return role, err
}

const listUserWorkspaces = `-- name: ListUserWorkspaces :many
SELECT w.id, w.name, wm.role, w.created_at
FROM workspace_members wm
JOIN workspaces w ON wm.workspace_id = w.id
WHERE wm.user_id = $1
AND w.deleted_at IS NULL
AND (
    $2 = ''
    OR LOWER(w.name) LIKE '%' || LOWER($2) || '%'
)
ORDER BY w.name
`

type ListUserWorkspacesParams struct {
	UserID int64       `json:"user_id"`
	Search interface{} `json:"search"`
}

type ListUserWorkspacesRow struct {
	ID        int64              `json:"id"`
	Name      string             `json:"name"`
	Role      UserRole           `json:"role"`
	CreatedAt pgtype.Timestamptz `json:"created_at"`
}

func (q *Queries) ListUserWorkspaces(ctx context.Context, arg ListUserWorkspacesParams) ([]ListUserWorkspacesRow, error) {
	rows, err := q.db.Query(ctx, listUserWorkspaces, arg.UserID, arg.Search)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListUserWorkspacesRow
	for rows.Next() {
		var i ListUserWorkspacesRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.Role,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listWorkspaceMembers = `-- name: ListWorkspaceMembers :many
SELECT u.id, u.fullname, u.username, u.email, wm.role, wm.joined_at
FROM workspace_members wm
JOIN users u ON wm.user_id = u.id
JOIN workspaces w ON wm.workspace_id = w.id
WHERE wm.workspace_id = $1 AND w.deleted_at IS NULL
ORDER BY wm.joined_at ASC
`

type ListWorkspaceMembersRow struct {
	ID       int64              `json:"id"`
	Fullname string             `json:"fullname"`
	Username string             `json:"username"`
	Email    string             `json:"email"`
	Role     UserRole           `json:"role"`
	JoinedAt pgtype.Timestamptz `json:"joined_at"`
}

func (q *Queries) ListWorkspaceMembers(ctx context.Context, workspaceID int64) ([]ListWorkspaceMembersRow, error) {
	rows, err := q.db.Query(ctx, listWorkspaceMembers, workspaceID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListWorkspaceMembersRow
	for rows.Next() {
		var i ListWorkspaceMembersRow
		if err := rows.Scan(
			&i.ID,
			&i.Fullname,
			&i.Username,
			&i.Email,
			&i.Role,
			&i.JoinedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const promoteMemberToAdmin = `-- name: PromoteMemberToAdmin :one
UPDATE workspace_members wm
SET role = 'ADMIN'
FROM workspaces w
WHERE wm.workspace_id = w.id AND wm.user_id = $1 AND wm.workspace_id = $2 AND wm.role != 'ADMIN' AND w.deleted_at IS NULL
RETURNING wm.workspace_id, wm.user_id, wm.role
`

type PromoteMemberToAdminParams struct {
	UserID      int64 `json:"user_id"`
	WorkspaceID int64 `json:"workspace_id"`
}

type PromoteMemberToAdminRow struct {
	WorkspaceID int64    `json:"workspace_id"`
	UserID      int64    `json:"user_id"`
	Role        UserRole `json:"role"`
}

func (q *Queries) PromoteMemberToAdmin(ctx context.Context, arg PromoteMemberToAdminParams) (PromoteMemberToAdminRow, error) {
	row := q.db.QueryRow(ctx, promoteMemberToAdmin, arg.UserID, arg.WorkspaceID)
	var i PromoteMemberToAdminRow
	err := row.Scan(&i.WorkspaceID, &i.UserID, &i.Role)
	return i, err
}

const removeWorkspaceMember = `-- name: RemoveWorkspaceMember :one
WITH deleted_project_members AS (
    DELETE FROM project_members pm
    USING projects p
    WHERE pm.project_id = p.id AND p.workspace_id = $1 AND pm.user_id = $2
),
deleted_workspace_member AS (
    DELETE FROM workspace_members
    WHERE workspace_id = $1 AND user_id = $2
    RETURNING workspace_id, user_id
)
SELECT dwm.workspace_id, dwm.user_id FROM deleted_workspace_member dwm
`

type RemoveWorkspaceMemberParams struct {
	WorkspaceID int64 `json:"workspace_id"`
	UserID      int64 `json:"user_id"`
}

type RemoveWorkspaceMemberRow struct {
	WorkspaceID int64 `json:"workspace_id"`
	UserID      int64 `json:"user_id"`
}

func (q *Queries) RemoveWorkspaceMember(ctx context.Context, arg RemoveWorkspaceMemberParams) (RemoveWorkspaceMemberRow, error) {
	row := q.db.QueryRow(ctx, removeWorkspaceMember, arg.WorkspaceID, arg.UserID)
	var i RemoveWorkspaceMemberRow
	err := row.Scan(&i.WorkspaceID, &i.UserID)
	return i, err
}
