// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: workspaces.sql

package sqlc

import (
	"context"
)

const createWorkspace = `-- name: CreateWorkspace :one
INSERT INTO workspaces(
    name
)
VALUES (
    $1
)
RETURNING id, name, created_at, updated_at
`

func (q *Queries) CreateWorkspace(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRow(ctx, createWorkspace, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByID = `-- name: GetWorkspaceByID :one
SELECT id, name, created_at, updated_at
FROM workspaces
WHERE id = $1
`

func (q *Queries) GetWorkspaceByID(ctx context.Context, id int64) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByID, id)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getWorkspaceByName = `-- name: GetWorkspaceByName :one
SELECT id, name, created_at, updated_at
FROM workspaces
WHERE name = $1
`

func (q *Queries) GetWorkspaceByName(ctx context.Context, name string) (Workspace, error) {
	row := q.db.QueryRow(ctx, getWorkspaceByName, name)
	var i Workspace
	err := row.Scan(
		&i.ID,
		&i.Name,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
