package service

import "errors"

var (
	ErrInvalidPassword               = errors.New("password must be atleast 8 and atmost 72 characters, containing uppercase, lowercase, numeric and special character")
	ErrInvalidFullName               = errors.New("name must be more than 3 characters")
	ErrInvalidEmail                  = errors.New("email is invalid")
	ErrInvalidCredentials            = errors.New("invalid credentials")
	ErrInvalidProjectName            = errors.New("project name must be between 3 and 100 characters")
	ErrInvalidDescription            = errors.New("description must be between 10 and 300 characters")
	ErrProjectNameTaken              = errors.New("a project with this name already exists for your account")
	ErrProjectAlreadyExists          = errors.New("project already exists")
	ErrWorkspaceNameTaken            = errors.New("this workspace name has already been taken")
	ErrInvalidWorkspaceName          = errors.New("workspace name must be more than 3 and less than 30 characters")
	ErrWorkspaceNotFound             = errors.New("workspace does not exist")
	ErrProjectMemberAlreadyExists    = errors.New("member already exists in this project")
	ErrProjectNotFound               = errors.New("project not found")
	ErrUserNotFound                  = errors.New("user not found")
	ErrProjectMemberValidationFailed = errors.New("cannot add user in this project")
	ErrUserNotProjectMember          = errors.New("user is not the member of this project")
	ErrWorkspaceMemberAlreadyExists  = errors.New("member already exists in this workspace")
	ErrWorkspaceAlreadyExists        = errors.New("workspace with this name already exists")
	ErrWorkspaceMemberNotFound       = errors.New("member does not exist in this workspace")
	ErrInvalidRole                   = errors.New("invalid role")
	ErrLeadUnchanged                 = errors.New("lead is already assigned")
	ErrInvalidLeadID                 = errors.New("invalid lead id")
	ErrInvalidWorkspaceID            = errors.New("invalid workspace id")
	ErrInvalidUserID                 = errors.New("invalid user id")
	ErrInvalidProjectID              = errors.New("invalid project id")
	ErrInvalidIssueID                = errors.New("invalid issue id")
	ErrIssueNotFound                 = errors.New("issue not found")
	ErrInvalidTitle                  = errors.New("invalid title")
	ErrInvalidStatus                 = errors.New("invalid status")
	ErrInvalidPriority               = errors.New("invalid priority")
	ErrInvalidAssignee               = errors.New("invalid assignee")
	ErrForbidden                     = errors.New("forbidden")
	ErrCommentNotFound               = errors.New("comment not found")
	ErrInvalidComment                = errors.New("invalid comment")
	ErrInvalidCommentID              = errors.New("invalid comment id")
	ErrInvalidActorID                = errors.New("invalid actor id")
	ErrInvalidActivityType           = errors.New("invalid activity type")
	ErrInvalidSearchQuery            = errors.New("invalid search query")
	ErrEmptyFile                     = errors.New("file is empty")
	ErrFileTooLarge                  = errors.New("file exceeds maximum allowed size of 10MB")
	ErrUnsupportedType               = errors.New("unsupported file content type")
	ErrDeleteFailed                  = errors.New("failed to delete file from storage")
	ErrCommentDoesNotBelongToIssue   = errors.New("comment does not belong to this issue")
	ErrAttachmentNotFound            = errors.New("attachment not found")
	ErrInvalidAttachmentID           = errors.New("invalid attachment id")
	ErrInvalidDueDate                = errors.New("invalid due date")
	ErrInvalidLabelName              = errors.New("label name is required and must be alteast 3 and atmost 20 characters.")
	ErrInvalidColor                  = errors.New("invalid label color")
	ErrInvalidLabelID                = errors.New("invalid label id")
	ErrNoLabelsProvided              = errors.New("at least one label must be provided")
	ErrLabelAlreadyExists            = errors.New("label already exist")
	ErrLabelNotFound                 = errors.New("label not found")
	ErrLabelDoesNotBelongToProject   = errors.New("label does not belong to project")
	ErrLabelNotAttached              = errors.New("label not attached")
)
